[distillation]
maxmemory="32G"
threshold=1e-9
cuda=true
type="classification"
precompute_teacher=true

[distillation.parameters]
epochs=10
optimizer="adam"
loss="MSE"
learning_rate=1e-3

[distillation.data]
format="mnist"
batchsize=64
presized=false
path="./data/mnist"

[distillation.teacher]
framework="onnx"
input_shape=[1, 1, 28, 28]
input_format="NCHW"
model="./configs/networks/mnist_conv_super.onnx"

[distillation.data.transform.teacher]
grayscale=true
mean=[0.1307]
std=[0.3081]
height=28
width=28
max_value=1

[distillation.data.transform.student]
grayscale=true
mean=[0.1307]
std=[0.3081]
height=28
width=28
max_value=1

[distillation.data.train]
shuffle=true

[distillation.data.validation]
shuffle=false